name: gfl-data-miner auto update bot

on:
  workflow_dispatch:
    inputs:
      cmdargs:
        description: 'Commandline Arguments'     
        required: false
        default: 'at tw kr jp us ch' 
        type: string
  push:
  schedule:
    - cron: '30 1,2-14/3 * * *'
    - cron: '0 4-13/3 * * 4'
    

jobs:
  gfl-data-miner-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Data Miner
        env:
          PERSONAL_TOKEN: ${{ secrets.TEST }}
          AUTHOR: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          DINGTALK_TOKEN: ${{ secrets.DINGTALK_TOKEN }}
        run: python data_miner.py ${{ inputs.cmdargs || 'at tw kr jp us ch' }} 
